# GitHub Actions workflow for deploying a Docker image to CapRover
name: Deploy to caprover instance.

# Global environment variables used throughout the workflow
env:
  CONTEXT_DIR: "./" # Directory context for Docker
  IMAGE_NAME: ${{ github.repository }} # Docker image name derived from the GitHub repository name
  DOCKERFILE: ./Dockerfile # Path to Dockerfile
  DOCKER_REGISTRY: ghcr.io # Docker registry to which the image will be pushed

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define the jobs in the workflow
jobs:
  # Job to handle building, testing, and publishing of the Docker image
  build-and-publish:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    permissions:
      contents: read
      packages: write
    steps:
      # Check out the repository code to the runner
      - uses: actions/checkout@v1

      # Cache dependencies for faster subsequent builds
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-vitejs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-vitejs-${{ hashFiles('**/package-lock.json') }}-

      # Set up the Node.js environment for the runner
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install project dependencies
      - run: npm ci

      # Build the project (Vite build)
      - run: npm run build --if-present

      # Run tests if they are available
      - run: npm run test --if-present

      # Log into the specified Docker registry
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for the Docker image
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build the Docker image and push it to the specified registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Deploy the Docker image to the CapRover instance
      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
        with:
          server: ${{ secrets.CAPROVER_SERVER }} # CapRover server URL
          app: ${{ secrets.APP_NAME }} # CapRover app name
          token: "${{ secrets.APP_TOKEN }}" # CapRover app token
          image: ${{ steps.meta.outputs.tags }} # Docker image to deploy
